/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PCBuilder;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro Guerrero A
 */
public class Builder extends javax.swing.JFrame {

    CPU c;
    MoBo m;
    RAM r;
    GPU g;
    HDD h;
    PSU p;

    /**
     * Creates new form Builder
     */
    public Builder() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int x = JOptionPane.showConfirmDialog(null, "¿Seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
                if (x == JOptionPane.YES_OPTION) {
                    if (ConteoUso.conteoMinutos == 0) {
                        JOptionPane.showMessageDialog(null, "¡Gracias por usar PC Builder!\nHa durado usando la aplicación " + ConteoUso.conteoSegundos + " segundos.");
                        System.exit(0);
                    } else if (ConteoUso.conteoMinutos == 1) {
                        JOptionPane.showMessageDialog(null, "¡Gracias por usar PC Builder!\nHa durado usando la aplicación " + ConteoUso.conteoMinutos + " minuto y " + ConteoUso.conteoSegundos + " segundos.");
                        System.exit(0);
                    } else {
                        JOptionPane.showMessageDialog(null, "¡Gracias por usar PC Builder!\nHa durado usando la aplicación " + ConteoUso.conteoMinutos + " minutos y " + ConteoUso.conteoSegundos + " segundos.");
                        System.exit(0);
                    }
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboCPU = new javax.swing.JComboBox<>();
        comboMoBo = new javax.swing.JComboBox<>();
        comboRam = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboGPU = new javax.swing.JComboBox<>();
        comboHDD = new javax.swing.JComboBox<>();
        comboPSU = new javax.swing.JComboBox<>();
        agregarListaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        agregarCotizacionButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Nueva PC");

        jLabel1.setText("Procesador");

        jLabel2.setText("Tarjeta Madre");

        jLabel3.setText("Memoria RAM");

        comboCPU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione Procesador--", "i7 7700K", "i7 7700", "i5 7600K", "i5 7600" }));
        comboCPU.setToolTipText("");
        comboCPU.setAutoscrolls(true);

        comboMoBo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione Tarjeta Madre--", "Z270", "B250", "H270", "Z170" }));

        comboRam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione Memoria RAM--", "8GB", "16GB", "32GB" }));

        jLabel4.setText("Tarjeta de Vídeo");

        jLabel5.setText("Disco Duro");

        jLabel6.setText("Fuente de Poder");

        comboGPU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione Tarjeta de Vídeo--", "GTX 1080Ti", "GTX 1080", "GTX 1070", "GTX 1060" }));

        comboHDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione Disco Duro--", "500GB", "1TB", "2TB", "4TB" }));

        comboPSU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione Fuente de Poder--", "500W", "600W", "750W", "800W" }));

        agregarListaButton.setText("Agregar a Lista");
        agregarListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarListaButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marca", "Modelo", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        agregarCotizacionButton.setText("Agregar a Cotización");
        agregarCotizacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCotizacionButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Atrás");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(agregarListaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboMoBo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboRam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboCPU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboHDD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboGPU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboPSU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(agregarCotizacionButton)
                        .addGap(147, 147, 147)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(comboGPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboMoBo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(comboHDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(comboPSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(agregarListaButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarCotizacionButton)
                    .addComponent(jButton1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarListaButtonActionPerformed
        try {
            DefaultTableModel tablaPartes = new DefaultTableModel();
            tablaPartes.addColumn("Marca");
            tablaPartes.addColumn("Modelo");
            tablaPartes.addColumn("Precio");
            for (int j = 0; j < 1; j++) {
                for (int i = 0; i < CPU.cpus.size(); i++) {
                    if (CPU.cpus.get(i).modelo == this.comboCPU.getSelectedItem()) {
                        c = CPU.cpus.get(i);
                        Object[] o = new Object[3];
                        o[0] = c.marca;
                        o[1] = c.modelo;
                        o[2] = c.precio;
                        tablaPartes.addRow(o);
                        this.jTable1.setModel(tablaPartes);
                    }
                }
                for (int i = 0; i < MoBo.mobos.size(); i++) {
                    if (MoBo.mobos.get(i).modelo == this.comboMoBo.getSelectedItem()) {
                        m = MoBo.mobos.get(i);
                        Object[] o = new Object[3];
                        o[0] = m.marca;
                        o[1] = m.modelo;
                        o[2] = m.precio;
                        tablaPartes.addRow(o);
                        this.jTable1.setModel(tablaPartes);
                    }
                }
                for (int i = 0; i < RAM.rams.size(); i++) {
                    if (RAM.rams.get(i).memoriaRAM == this.comboRam.getSelectedItem()) {
                        r = RAM.rams.get(i);
                        Object[] o = new Object[3];
                        o[0] = r.marca;
                        o[1] = r.modelo;
                        o[2] = r.precio;
                        tablaPartes.addRow(o);
                        this.jTable1.setModel(tablaPartes);
                    }
                }
                for (int i = 0; i < GPU.gpus.size(); i++) {
                    if (GPU.gpus.get(i).modelo == this.comboGPU.getSelectedItem()) {
                        g = GPU.gpus.get(i);
                        Object[] o = new Object[3];
                        o[0] = g.marca;
                        o[1] = g.modelo;
                        o[2] = g.precio;
                        tablaPartes.addRow(o);
                        this.jTable1.setModel(tablaPartes);
                    }
                }
                for (int i = 0; i < HDD.hdds.size(); i++) {
                    if (HDD.hdds.get(i).memoria == this.comboHDD.getSelectedItem()) {
                        h = HDD.hdds.get(i);
                        Object[] o = new Object[3];
                        o[0] = h.marca;
                        o[1] = h.modelo;
                        o[2] = h.precio;
                        tablaPartes.addRow(o);
                        this.jTable1.setModel(tablaPartes);
                    }
                }
                for (int i = 0; i < PSU.psus.size(); i++) {
                    if (PSU.psus.get(i).wattage == this.comboPSU.getSelectedItem()) {
                        p = PSU.psus.get(i);
                        Object[] o = new Object[3];
                        o[0] = p.marca;
                        o[1] = p.modelo;
                        o[2] = p.precio;
                        tablaPartes.addRow(o);
                        this.jTable1.setModel(tablaPartes);
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error");
        }

    }//GEN-LAST:event_agregarListaButtonActionPerformed

    private void agregarCotizacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCotizacionButtonActionPerformed
        try {
            Cotizacion cot = new Cotizacion();
            cot.setCpu(c);
            cot.setMobo(m);
            cot.setRam(r);
            cot.setGpu(g);
            cot.setHdd(h);
            cot.setPsu(p);
            if (c != null || m != null || r != null || g != null || h != null || p != null) {
                JOptionPane.showMessageDialog(null, "Se ha enviado sus partes a Cotización");
                new MenuPrincipal().setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Por favor, agregar productos a la lista seleccionando uno en cualquier categoría y presionando Agregar a Lista");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hubo un error en la cotización");
            new MenuPrincipal().setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_agregarCotizacionButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MenuPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Builder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Builder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Builder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Builder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Builder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCotizacionButton;
    private javax.swing.JButton agregarListaButton;
    private javax.swing.JComboBox<String> comboCPU;
    private javax.swing.JComboBox<String> comboGPU;
    private javax.swing.JComboBox<String> comboHDD;
    private javax.swing.JComboBox<String> comboMoBo;
    private javax.swing.JComboBox<String> comboPSU;
    private javax.swing.JComboBox<String> comboRam;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
